services:
  unbound:
    image: klutchell/unbound:latest
    hostname: unbound
    ports:
      - target: 5335
        published: 5335
        protocol: tcp
        mode: ingress
      - target: 5335
        published: 5335
        protocol: udp
        mode: host
    deploy:
      mode: global
    cap_add:
      - NET_ADMIN
    networks:
      - swarm-network
    volumes:
      - $DOCKERDIR/appdata/pihole/unbound/custom.conf.d:/etc/unbound/custom.conf.d
    healthcheck:
      test: ["CMD", "drill", "@127.0.0.1", "dnssec.works"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
  pihole:
    image: pihole/pihole:latest
    hostname: pihole
    networks:
      - swarm-network
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: ingress
      - target: 53
        published: 53
        protocol: udp
        mode: ingress
#      - target: 67
#        published: 67
#        protocol: udp
#        mode: host
      - target: 80
        published: 8091
        protocol: tcp
        mode: ingress
    environment:
      - WEBPASSWORD=
      - TZ=$TZ
      - PIHOLE_DNS=172.31.0.1#5335
      #- PIHOLE_DNS=192.168.1.1
      - REV_SERVER=true
      - REV_SERVER_CIDR=192.168.1.0/24 #Update these fields to match your environment
      - REV_SERVER_TARGET=192.168.1.1
      - REV_SERVER_DOMAIN=$HOSTNAME.$DOMAIN
      - DNSSEC=yes
      - FTLCONF_BLOCK_ICLOUD_PR=false
      - TEMPERATUREUNIT=f
#    depends_on:
#      - unbound
    cap_add:
      - NET_ADMIN
    # Volumes store your data between container upgrades
    volumes:
      - $DOCKERDIR/appdata/pihole/pihole-data:/etc/pihole/
      - $DOCKERDIR/appdata/pihole/pihole-dnsmasq:/etc/dnsmasq.d/
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.pihole.rule=Host(`pihole.$HOSTNAME.$DOMAIN`)
        - traefik.http.routers.pihole.entrypoints=websecure
        - traefik.http.routers.pihole.tls=true
        - traefik.http.routers.pihole.tls.certresolver=cloudflare
        - traefik.http.routers.pihole.service=pihole
        - traefik.http.services.pihole.loadbalancer.server.port=80
        - traefik.http.middlewares.add-pihole-admin.replacepath.path=/admin
        - traefik.http.middlewares.add-admin-prefix.addprefix.prefix=/admin
        - traefik.http.routers.pihole.middlewares=add-admin-prefix
        # 53/udp
        # - traefik.udp.routers.pihole-dns-udp.entrypoints=dns-udp
        # - traefik.udp.routers.pihole-dns-udp.service=pihole-dns-udp
        # - traefik.udp.services.pihole-dns-udp.loadbalancer.server.port=53
        # 53/tcp
        # - traefik.tcp.routers.pihole-dns-tcp.rule=HostSNI(`*`)
        # - traefik.tcp.routers.pihole-dns-tcp.entrypoints=dns-tcp
        # - traefik.tcp.routers.pihole-dns-tcp.service=pihole-dns-tcp
        # - traefik.tcp.services.pihole-dns-tcp.loadbalancer.server.port=53

networks:
  swarm-network:
    external: true
