services:
  unbound:
    image: klutchell/unbound:latest
    hostname: unbound
    ports:
      - 5053:53/udp
      - 5053:53
    deploy:
      replicas: 3
      #placement:
      #  constraints: [node.role == manager]
    networks:
      - traefik-public

    #volumes:
    #  - $DOCKERDIR/appdata/pihole/unbound/unbound.conf:/etc/unbound/unbound.conf

  pihole:
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: ingress
      - target: 53
        published: 53
        protocol: udp
        mode: ingress
#      - target: 67
#        published: 67
#        protocol: udp
#        mode: host
#      - target: 80
#        published: 8901
#        protocol: tcp
#        mode: ingress

    environment:
      - WEBPASSWORD=
      - TZ=$TZ
      #- PIHOLE_DNS_=172.16.0.1#5053
      - PIHOLD_DNS_=1.1.1.1
      - REV_SERVER=true
      - REV_SERVER_CIDR=192.168.1.0/24 #Update these fields to match your environment
      - REV_SERVER_TARGET=192.168.1.1
      - REV_SERVER_DOMAIN=$DOMAIN
      - DNSSEC=true
      - TEMPERATUREUNIT=f
    depends_on:
      - unbound
    # Volumes store your data between container upgrades
    volumes:
      - $DOCKERDIR/appdata/pihole/pihole-data:/etc/pihole/
      - $DOCKERDIR/appdata/pihole/pihole-dnsmasq:/etc/dnsmasq.d/
    networks:
      - traefik-public


    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.pihole.rule=Host(`pihole.$HOSTNAME.$DOMAIN`)
        - traefik.http.routers.pihole.entrypoints=websecure
        - traefik.http.routers.pihole.tls=true
        - traefik.http.routers.pihole.tls.certresolver=cloudflare
        - traefik.http.routers.pihole.service=pihole
        - traefik.http.services.pihole.loadbalancer.server.port=80
        - traefik.http.middlewares.pihole.addprefix.prefix=/admin/
        # 53/udp
        # - traefik.udp.routers.pihole-dns-udp.entrypoints=dns-udp
        # - traefik.udp.routers.pihole-dns-udp.service=pihole-dns-udp
        # - traefik.udp.services.pihole-dns-udp.loadbalancer.server.port=53
        # 53/tcp
        # - traefik.tcp.routers.pihole-dns-tcp.rule=HostSNI(`*`)
        # - traefik.tcp.routers.pihole-dns-tcp.entrypoints=dns-tcp
        # - traefik.tcp.routers.pihole-dns-tcp.service=pihole-dns-tcp
        # - traefik.tcp.services.pihole-dns-tcp.loadbalancer.server.port=53

networks:
  traefik-public:
    external: true
