services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: "mongo:6.0"  
    restart: "on-failure"
    networks:
      - graylog
    volumes:
      - "/volume1/docker/appdata/graylog/mongodb/data:/data/db"
      - "/volume1/docker/appdata/graylog/mongodb/config:/data/configdb"  
    deploy:
      mode: replicated 
      replicas: 1

  # For DataNode setup, graylog starts with a preflight UI, this is a change from just using OpenSearch/Elasticsearch.
  # Please take a look at the README at the top of this repo or the regular docs for more info.
  # Graylog Data Node: https://hub.docker.com/r/graylog/graylog-datanode
  datanode:
    image: "graylog/graylog-datanode:latest"
    hostname: "graylog-datanode"
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      # GRAYLOG_DATANODE_PASSWORD_SECRET and GRAYLOG_PASSWORD_SECRET MUST be the same value
      GRAYLOG_DATANODE_PASSWORD_SECRET: "FbWFPQP3Ef4DZMe5XSoC8KXkOaoLoN6GNyfs6FICHY49q7LAnAipq9P9jdhrYbjCyM3hpdGH2heZZkwU1H1z3xrIuDvlwxck"
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8999:8999/tcp"   # DataNode API
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    networks:
      - bridge_ipv6
    volumes:
      - "/volume1/docker/appdata/graylog/graylog-datanode:/var/lib/graylog-datanode"
    deploy:
      mode: replicated 
      replicas: 1

  # Graylog: https://hub.docker.com/r/graylog/graylog-enterprise
  graylog:
    hostname: "greylog-server"
    image: "graylog/graylog:6.1:latest"
    depends_on:
      mongodb:
        condition: "service_started"
      datanode:
        condition: "service_started"
    entrypoint: "/usr/bin/tini --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      # GRAYLOG_DATANODE_PASSWORD_SECRET and GRAYLOG_PASSWORD_SECRET MUST be the same value
      GRAYLOG_PASSWORD_SECRET: "FbWFPQP3Ef4DZMe5XSoC8KXkOaoLoN6GNyfs6FICHY49q7LAnAipq9P9jdhrYbjCyM3hpdGH2heZZkwU1H1z3xrIuDvlwxck"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9020"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9020/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
    - "5044:5044/tcp"   # Beats
    - "5140:5140/udp"   # Syslog
    - "5140:5140/tcp"   # Syslog
    - "5555:5555/tcp"   # RAW TCP
    - "5555:5555/udp"   # RAW UDP
    - "9020:9020/tcp"   # Server API
    - "12201:12201/tcp" # GELF TCP
    - "12201:12201/udp" # GELF UDP
    #- "10000:10000/tcp" # Custom TCP port
    #- "10000:10000/udp" # Custom UDP port
    - "13301:13301/tcp" # Forwarder data
    - "13302:13302/tcp" # Forwarder config
    networks:
      - bridge_ipv6
    volumes:
      - "/volume1/docker/appdata/graylog/data:/usr/share/graylog/data/data"
    deploy:
      mode: replicated 
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.graylog.rule=Host(`graylog.$DOMAIN`)
        - traefik.http.routers.graylog.entrypoints=websecure
        - traefik.http.routers.graylog.tls=true
        - traefik.http.routers.graylog.tls.certresolver=cloudflare
        - traefik.http.routers.graylog.service=graylog
        - traefik.http.services.graylog.loadbalancer.server.port=9020

networks:
  bridge_ipv6:
    external: true

secrets:
  password:
    external: true