---
- name: Reboot Raspberry Pi Cluster Nodes
  hosts: orange
  serial: 1
  become: yes
  tasks:
    - name: Reboot the node
      ansible.builtin.reboot:
        reboot_timeout: 360

    - name: Wait for the node to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 300