- name: Gather and display Docker host info from each node
  hosts: orange
  gather_facts: no
  become: yes
  tasks:
    - name: Get Docker host info
      community.docker.docker_host_info:
      register: docker_host_info_result

    - name: Display full Docker host info for the node
      debug:
        var: docker_host_info_result
