- name: Gather Docker host info including swarm details
  hosts: orange
  gather_facts: no
  become: yes
  tasks:
    - name: Get Docker host info
      community.docker.docker_host_info:
      register: docker_host_info_result

    - name: Set local swarm node fact based on Docker host info
      set_fact:
        swarm_node_info:
          hostname: "{{ inventory_hostname }}"
          in_swarm: "{{ docker_host_info_result.info.Swarm.LocalNodeState == 'active' }}"
          node_id: "{{ docker_host_info_result.info.Swarm.NodeID | default('not_in_swarm') }}"
          role: "{{ docker_host_info_result.info.Swarm.ControlAvailable | default(false) | bool | ternary('manager', 'worker') }}"

    - name: Debug - Display Docker swarm info for the node
      debug:
        msg: "Host {{ inventory_hostname }}: Node ID={{ swarm_node_info.node_id }}, In Swarm={{ swarm_node_info.in_swarm }}, Role={{ swarm_node_info.role }}"
