- name: Gather Docker Swarm details and set local facts
  hosts: orange
  gather_facts: no
  become: yes
  tasks:
    - name: Get Docker host info
      community.docker.docker_host_info:
      register: docker_host_info_result

    - name: Set local swarm node fact based on Docker host info
      set_fact:
        swarm_node_info:
          hostname: "{{ inventory_hostname }}"
          node_id: "{{ docker_host_info_result.host_info.Swarm.NodeID }}"
          in_swarm: "{{ docker_host_info_result.host_info.Swarm.LocalNodeState == 'active' }}"
          role: "{{ docker_host_info_result.host_info.Swarm.ControlAvailable | bool | ternary('manager', 'worker') }}"

    - name: Debug - Display limited Docker swarm info for the node
      debug:
        msg: >
          Host: {{ swarm_node_info.hostname }},
          In Swarm: {{ swarm_node_info.in_swarm }},
          Node ID: {{ swarm_node_info.node_id }},
          Role: {{ swarm_node_info.role }}

- name: Aggregate swarm node information from all nodes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Build global swarm nodes list from host facts
      set_fact:
        global_swarm_nodes: "{{ groups['orange'] | map('extract', hostvars, 'swarm_node_info') | list }}"

    - name: Debug - Display global swarm nodes list
      debug:
        var: global_swarm_nodes

- name: Define docker_gwbridge network configuration
  hosts: orange
  gather_facts: no
  tasks:
    - name: Set docker_gwbridge configuration fact
      set_fact:
        docker_gwbridge_config:
          driver: "bridge"
          ipam_config:
            - subnet: "172.22.0.0/24"
            - subnet: "2600:1702:6650:9b20:22::/80"
          enable_ipv6: true
          driver_options:
            com.docker.network.bridge.name: "docker_gwbridge"
            com.docker.network.bridge.gateway_mode_ipv6: "routed"
            com.docker.network.bridge.gateway_ipv6: "2600:1702:6650:9b20:22::1"

    - name: Debug - Display docker_gwbridge configuration fact
      debug:
        msg: "docker_gwbridge_config: {{ docker_gwbridge_config }}"


