- name: Identify swarm nodes and their roles
  hosts: "{{ groups['orange'][0] }}"   # Use the first node (assumed manager) to query the swarm
  gather_facts: no
  become: yes
  tasks:
    - name: Retrieve swarm node list with roles
      command: >
        docker node ls --format "{{ '{{.ID}} {{.Hostname}} {{if .ManagerStatus}}manager{{else}}worker{{end}}' }}"
      register: swarm_node_list
      changed_when: false

    - name: Debug - Raw swarm node list output
      debug:
        msg: "{{ swarm_node_list.stdout_lines }}"

    - name: Parse swarm nodes into structured list
      set_fact:
        global_swarm_nodes: >-
          {{
            swarm_node_list.stdout_lines
            | map('split', ' ')
            | map('zip', ['id', 'hostname', 'role'])
            | map('items2dict')
            | list
          }}
      delegate_to: localhost

    - name: Debug - Display parsed swarm nodes
      debug:
        msg: "Swarm nodes: {{ global_swarm_nodes }}"
