- name: Gather swarm node info on each node
  hosts: orange
  gather_facts: no
  become: yes
  tasks:
    - name: Get Docker swarm info
      command: docker info --format "{{ '{{.Swarm.NodeID}} {{.Swarm.ControlAvailable}}' }}"
      register: docker_info
      changed_when: false
      ignore_errors: yes

    - name: Set local swarm node fact
      set_fact:
        swarm_node_info: >-
          {{
            {
              'hostname': inventory_hostname,
              'node_id': (docker_info.stdout.split()[0]) if (docker_info.stdout.split() | length) > 0 else 'not_in_swarm',
              'role': ( 'manager' if ((docker_info.stdout.split() | length) > 1 and docker_info.stdout.split()[1] == 'true') else 'worker' )
            }
          }}

    - name: Debug - Show local swarm node info
      debug:
        msg: "Host {{ inventory_hostname }}: Node ID={{ swarm_node_info.node_id }}, Role={{ swarm_node_info.role }}"
