- name: Determine the current Swarm leader
  hosts: orange
  gather_facts: no
  become: yes
  tasks:
    - name: Debug - Show current inventory hostname
      debug:
        msg: "Running on {{ inventory_hostname }}"

    - name: Check if Docker is installed
      command: docker --version
      register: docker_version
      changed_when: false
      ignore_errors: true

    - name: Fail if Docker is not installed
      fail:
        msg: "Docker is not installed on {{ inventory_hostname }}."
      when: docker_version.rc != 0

    - name: Check if Docker is running
      command: systemctl is-active docker
      register: docker_status
      changed_when: false
      ignore_errors: true

    - name: Fail if Docker is not running
      fail:
        msg: "Docker is not running on {{ inventory_hostname }}. Ensure Docker is installed and running."
      when: docker_status.stdout != "active"

    - name: Check if this node is part of a Swarm
      command: docker info --format "{{ '{{.Swarm.LocalNodeState}}' }}"
      register: swarm_status
      changed_when: false
      ignore_errors: true

    - name: Fail if this node is not part of a Swarm
      fail:
        msg: "This node is not part of a Swarm. Ensure the node has joined a Swarm."
      when: swarm_status.stdout not in ["active", "manager"]

    - name: Get the current Swarm leader (run on first available manager)
      run_once: true
      command: docker node inspect self --format "{{ '{{.ManagerStatus.Leader}}' }}"
      register: leader_status
      changed_when: false
      ignore_errors: true

    - name: Ensure leader_status is valid
      run_once: true
      fail:
        msg: "Failed to detect Swarm leader. leader_status.stdout is empty or invalid."
      when: leader_status.stdout is not defined or leader_status.stdout | trim == ""

    - name: Extract and store Swarm leader
      run_once: true
      set_fact:
        swarm_leader: "{{ inventory_hostname }}"
      when: leader_status.stdout | trim == "true"

    - name: Ensure swarm_leader is defined before distributing
      run_once: true
      fail:
        msg: "Swarm leader variable is still undefined. Something went wrong with leader detection."
      when: swarm_leader is not defined

    - name: Distribute Swarm leader fact to all nodes
      set_fact:
        swarm_leader: "{{ hostvars[ansible_play_hosts[0]]['swarm_leader'] }}"

- name: Define network configuration
  hosts: orange
  gather_facts: no
  tasks:
    - name: Set docker_gwbridge network configuration
      set_fact:
        docker_gwbridge_config: >
          docker network create
          --driver bridge
          --subnet=172.22.0.0/24
          --ipv6
          --subnet=2600:1702:6650:9b20:22::/80
          --opt com.docker.network.bridge.name=docker_gwbridge
          docker_gwbridge

- name: Fetch and distribute Swarm join tokens
  hosts: "{{ swarm_leader }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Fetch Swarm join tokens
      command: docker swarm join-token -q {{ item }}
      register: swarm_tokens
      changed_when: false
      loop:
        - worker
        - manager

    - name: Distribute Swarm join tokens to all nodes
      set_fact:
        worker_token: "{{ swarm_tokens.results[0].stdout }}"
        manager_token: "{{ swarm_tokens.results[1].stdout }}"
        swarm_leader_ip: "{{ ansible_host | default(inventory_hostname) }}"

- name: Update Non-Leader Nodes
  hosts: orange
  serial: 1
  become: yes
  gather_facts: yes
  tasks:
    - name: Skip leader node (processed last)
      meta: end_play
      when: inventory_hostname == swarm_leader

    - name: Demote non-leader managers
      command: docker node demote {{ inventory_hostname }}
      when: "'manager' in node_role.stdout and inventory_hostname != swarm_leader"

    - name: Leave the Swarm (abort if it fails)
      command: docker swarm leave
      register: swarm_leave_result
      failed_when: swarm_leave_result.rc != 0

    - name: Remove old docker_gwbridge network
      command: docker network rm docker_gwbridge
      ignore_errors: yes

    - name: Create new docker_gwbridge network
      command: "{{ docker_gwbridge_config }}"

    - name: Rejoin the Swarm as a worker
      command: docker swarm join --token {{ worker_token }} {{ swarm_leader_ip }}:2377
      when: inventory_hostname != swarm_leader

    - name: Promote back to manager if originally a manager
      command: docker node promote {{ inventory_hostname }}
      when: "'manager' in node_role.stdout and inventory_hostname != swarm_leader"

- name: Update Swarm Leader (Processed Last)
  hosts: "{{ swarm_leader }}"
  serial: 1
  become: yes
  tasks:
    - name: Ensure another manager exists before demoting leader
      command: docker node promote {{ groups['orange'] | difference([inventory_hostname]) | first }}
      run_once: true

    - name: Demote Swarm leader
      command: docker node demote {{ inventory_hostname }}

    - name: Leave the Swarm (abort if it fails)
      command: docker swarm leave
      register: swarm_leave_result
      failed_when: swarm_leave_result.rc != 0

    - name: Remove old docker_gwbridge network
      command: docker network rm docker_gwbridge
      ignore_errors: yes

    - name: Create new docker_gwbridge network
      command: "{{ docker_gwbridge_config }}"

    - name: Rejoin leader as a manager
      command: docker swarm join --token {{ manager_token }} {{ groups['orange'] | difference([inventory_hostname]) | first }}:2377

    - name: Promote leader back to manager
      command: docker node promote {{ inventory_hostname }}

    - name: Fetch new Swarm join tokens
      command: docker swarm join-token -q {{ item }}
      register: new_swarm_tokens
      changed_when: false
      loop:
        - worker
        - manager

    - name: Distribute new Swarm join tokens to all nodes
      set_fact:
        worker_token: "{{ new_swarm_tokens.results[0].stdout }}"
        manager_token: "{{ new_swarm_tokens.results[1].stdout }}"
