- name: Determine the current Swarm leader
  hosts: orange
  gather_facts: no
  become: yes
  tasks:
    - name: Ensure at least one manager exists before proceeding
      fail:
        msg: "No Swarm managers detected. Ensure at least one node is a manager."
      when: groups['orange'] | select('search', 'manager') | list | length == 0

    - name: Get Swarm manager info (run only on first available manager)
      community.docker.docker_swarm_info:
      register: swarm_info
      changed_when: false
      ignore_errors: true
      run_once: true
      when: inventory_hostname in groups['orange']

    - name: Debug - Show full Swarm info output
      debug:
        var: swarm_info
      when: swarm_info is defined

    - name: Identify Swarm leader from manager nodes
      set_fact:
        swarm_leader: "{{ inventory_hostname }}"
      when:
        - swarm_info is defined
        - swarm_info.swarm_facts is defined
        - swarm_info.swarm_facts.ID is defined
        - swarm_info.swarm_facts.JoinTokens is defined  # Ensures node is part of Swarm

- name: Identify and distribute Swarm leader
  hosts: orange
  gather_facts: no
  tasks:
    - name: Find first detected leader and store on all nodes
      set_fact:
        swarm_leader: "{{ groups['orange'] | map('extract', hostvars, 'swarm_leader') | select('defined') | list | first | default('') }}"

    - name: Debug - Confirm final Swarm leader
      debug:
        msg: "Final Swarm leader is {{ swarm_leader }}"

    - name: Fail if no Swarm leader was found
      fail:
        msg: "No Swarm leader was detected. Ensure that at least one manager is online."
      when: swarm_leader | length == 0

- name: Define network configuration
  hosts: orange
  gather_facts: no
  tasks:
    - name: Set docker_gwbridge network configuration
      set_fact:
        docker_gwbridge_config:
          driver: bridge
          ipam_options:
            - subnet: "172.22.0.0/24"
            - subnet: "2600:1702:6650:9b20:22::/80"
          enable_ipv6: true
          options:
            com.docker.network.bridge.name: docker_gwbridge

- name: Fetch and distribute Swarm join tokens
  hosts: "{{ swarm_leader }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Fetch Swarm join tokens
      community.docker.docker_swarm_info:
      register: swarm_tokens
      changed_when: false

    - name: Distribute Swarm join tokens to all nodes
      set_fact:
        worker_token: "{{ swarm_tokens.worker_join_token }}"
        manager_token: "{{ swarm_tokens.manager_join_token }}"
        swarm_leader_ip: "{{ ansible_host | default(inventory_hostname) }}"

- name: Update Non-Leader Nodes
  hosts: orange
  serial: 1
  become: yes
  gather_facts: no
  tasks:
    - name: Skip leader node (processed last)
      meta: end_play
      when: inventory_hostname == swarm_leader

    - name: Get node role (only managers)
      community.docker.docker_swarm_info:
      register: node_role_info
      changed_when: false
      ignore_errors: true
      when: "'manager' in group_names"

    - name: Debug - Show node role
      debug:
        msg: "{{ inventory_hostname }} role: {{ node_role_info.swarm_facts.NodeRole | default('UNDEFINED') }}"
      when: node_role_info is defined and "'manager' in group_names"

    - name: Demote if this node is a manager
      community.docker.docker_node:
        hostname: "{{ inventory_hostname }}"
        role: worker
      when: 
        - "'manager' in group_names"
        - node_role_info is defined
        - node_role_info.swarm_facts is defined
        - node_role_info.swarm_facts.NodeRole == "manager"
        - inventory_hostname != swarm_leader

    - name: Leave Swarm (abort if it fails)
      community.docker.docker_swarm:
        state: absent
      register: swarm_leave_result
      failed_when: swarm_leave_result.changed == false

    - name: Remove old docker_gwbridge network
      community.docker.docker_network:
        name: docker_gwbridge
        state: absent
      ignore_errors: yes

    - name: Create new docker_gwbridge network
      community.docker.docker_network:
        name: docker_gwbridge
        driver: "{{ docker_gwbridge_config.driver }}"
        ipam_options: "{{ docker_gwbridge_config.ipam_options }}"
        options: "{{ docker_gwbridge_config.options }}"
        enable_ipv6: "{{ docker_gwbridge_config.enable_ipv6 }}"

    - name: Rejoin Swarm as worker
      community.docker.docker_swarm:
        state: present
        join_token: "{{ worker_token }}"
        remote_addrs:
          - "{{ swarm_leader_ip }}"
      when: inventory_hostname != swarm_leader

    - name: Promote back to manager if originally a manager
      community.docker.docker_node:
        hostname: "{{ inventory_hostname }}"
        role: manager
      when: 
        - "'manager' in group_names"
        - node_role_info is defined
        - node_role_info.swarm_facts is defined
        - node_role_info.swarm_facts.NodeRole == "manager"
        - inventory_hostname != swarm_leader

- name: Update Swarm Leader (Processed Last)
  hosts: "{{ swarm_leader }}"
  serial: 1
  become: yes
  tasks:
    - name: Ensure another manager exists before demoting leader
      community.docker.docker_node:
        hostname: "{{ groups['orange'] | difference([inventory_hostname]) | first }}"
        role: manager
      run_once: true

    - name: Demote Swarm leader
      community.docker.docker_node:
        hostname: "{{ inventory_hostname }}"
        role: worker

    - name: Leave the Swarm (abort if it fails)
      community.docker.docker_swarm:
        state: absent
      register: swarm_leave_result
      failed_when: swarm_leave_result.changed == false

    - name: Remove old docker_gwbridge network
      community.docker.docker_network:
        name: docker_gwbridge
        state: absent
      ignore_errors: yes

    - name: Create new docker_gwbridge network
      community.docker.docker_network:
        name: docker_gwbridge
        driver: "{{ docker_gwbridge_config.driver }}"
        ipam_options: "{{ docker_gwbridge_config.ipam_options }}"
        options: "{{ docker_gwbridge_config.options }}"
        enable_ipv6: "{{ docker_gwbridge_config.enable_ipv6 }}"

    - name: Rejoin leader as a manager
      community.docker.docker_swarm:
        state: present
        join_token: "{{ manager_token }}"
        remote_addrs:
          - "{{ groups['orange'] | difference([inventory_hostname]) | first }}"

    - name: Promote leader back to manager
      community.docker.docker_node:
        hostname: "{{ inventory_hostname }}"
        role: manager

    - name: Fetch new Swarm join tokens
      community.docker.docker_swarm_info:
      register: new_swarm_tokens
      changed_when: false

    - name: Distribute new Swarm join tokens
      set_fact:
        worker_token: "{{ new_swarm_tokens.worker_join_token }}"
        manager_token: "{{ new_swarm_tokens.manager_join_token }}"
