- name: Determine the current Swarm leader
  hosts: orange
  gather_facts: no
  become: yes
  tasks:
    - name: Get Swarm leader status on each node
      command: docker node inspect self --format "{{ '{{.ManagerStatus.Leader}}' }}"
      register: leader_status
      changed_when: false
      ignore_errors: true

    - name: Debug - Show leader status output
      debug:
        msg: "{{ inventory_hostname }} leader status: {{ leader_status.stdout | default('UNDEFINED') }}"

    - name: Mark this node as leader if detected
      set_fact:
        detected_leader: "{{ inventory_hostname }}"
      when: leader_status.stdout | trim == "true"

- name: Select the first detected leader and store it
  hosts: orange
  gather_facts: no
  tasks:
    - name: Ensure a leader was found
      run_once: true
      fail:
        msg: "No Swarm leader detected. Check Swarm quorum."
      when: groups['orange'] | map('extract', hostvars, 'detected_leader') | select('defined') | list | length == 0

    - name: Store the first detected leader globally
      run_once: true
      set_fact:
        swarm_leader: "{{ groups['orange'] | map('extract', hostvars, 'detected_leader') | select('defined') | list | first }}"
      delegate_to: localhost
      delegate_facts: true

    - name: Debug - Confirm final detected leader
      run_once: true
      debug:
        msg: "Final Swarm leader is {{ hostvars['localhost']['swarm_leader'] }}"

- name: Define network configuration
  hosts: orange
  gather_facts: no
  tasks:
    - name: Set docker_gwbridge network configuration
      set_fact:
        docker_gwbridge_config: >
          docker network create
          --driver bridge
          --subnet=172.22.0.0/24
          --ipv6
          --subnet=2600:1702:6650:9b20:22::/80
          --opt com.docker.network.bridge.name=docker_gwbridge
          docker_gwbridge

- name: Fetch and distribute Swarm join tokens
  hosts: "{{ hostvars['localhost']['swarm_leader'] }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Fetch Swarm join tokens
      command: docker swarm join-token -q {{ item }}
      register: swarm_tokens
      changed_when: false
      loop:
        - worker
        - manager

    - name: Distribute Swarm join tokens to all nodes
      set_fact:
        worker_token: "{{ swarm_tokens.results[0].stdout }}"
        manager_token: "{{ swarm_tokens.results[1].stdout }}"
        swarm_leader_ip: "{{ ansible_host | default(inventory_hostname) }}"

- name: Update Non-Leader Nodes
  hosts: orange
  serial: 1
  become: yes
  gather_facts: yes
  tasks:
    - name: Skip leader node (processed last)
      meta: end_play
      when: inventory_hostname == hostvars['localhost']['swarm_leader']

    - name: Demote non-leader managers
      command: docker node demote {{ inventory_hostname }}
      when: "'manager' in node_role.stdout and inventory_hostname != hostvars['localhost']['swarm_leader']"

    - name: Leave the Swarm (abort if it fails)
      command: docker swarm leave
      register: swarm_leave_result
      failed_when: swarm_leave_result.rc != 0

    - name: Remove old docker_gwbridge network
      command: docker network rm docker_gwbridge
      ignore_errors: yes

    - name: Create new docker_gwbridge network
      command: "{{ docker_gwbridge_config }}"

    - name: Rejoin the Swarm as a worker
      command: docker swarm join --token {{ worker_token }} {{ swarm_leader_ip }}:2377
      when: inventory_hostname != hostvars['localhost']['swarm_leader']

    - name: Promote back to manager if originally a manager
      command: docker node promote {{ inventory_hostname }}
      when: "'manager' in node_role.stdout and inventory_hostname != hostvars['localhost']['swarm_leader']"

- name: Update Swarm Leader (Processed Last)
  hosts: "{{ hostvars['localhost']['swarm_leader'] }}"
  serial: 1
  become: yes
  tasks:
    - name: Ensure another manager exists before demoting leader
      command: docker node promote {{ groups['orange'] | difference([inventory_hostname]) | first }}
      run_once: true

    - name: Demote Swarm leader
      command: docker node demote {{ inventory_hostname }}

    - name: Leave the Swarm (abort if it fails)
      command: docker swarm leave
      register: swarm_leave_result
      failed_when: swarm_leave_result.rc != 0

    - name: Remove old docker_gwbridge network
      command: docker network rm docker_gwbridge
      ignore_errors: yes

    - name: Create new docker_gwbridge network
      command: "{{ docker_gwbridge_config }}"

    - name: Rejoin leader as a manager
      command: docker swarm join --token {{ manager_token }} {{ groups['orange'] | difference([inventory_hostname]) | first }}:2377

    - name: Promote leader back to manager
      command: docker node promote {{ inventory_hostname }}

    - name: Fetch new Swarm join tokens
      command: docker swarm join-token -q {{ item }}
      register: new_swarm_tokens
      changed_when: false
      loop:
        - worker
        - manager

    - name: Distribute new Swarm join tokens to all nodes
      set_fact:
        worker_token: "{{ new_swarm_tokens.results[0].stdout }}"
        manager_token: "{{ new_swarm_tokens.results[1].stdout }}"
