services:
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel debug
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 60s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - $DOCKERDIR/appdata/redis/data:/data
    networks:
      - traefik-public
    deploy:
      mode: replicated 
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.http.routers.redis.rule=Host(`redis.$HOST.$DOMAIN`)
        - traefik.http.routers.redis.entrypoints=redis
        - traefik.http.routers.redis.tls=true
        - traefik.http.routers.redis.service=redis
        - traefik.http.services.redis.loadbalancer.server.port=6379

networks:
  traefik-public:
    external: true