services:
  ha:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    ports:
      - 8123:8123
    volumes:
      - $DOCKERDIR/appdata/home-assistant/config:/config
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    networks:
      - traefik-public
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - S6_BEHAVIOUR_IF_STAGE2_FAILS=2
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - S6_CMD_WAIT_FOR_SERVICES=1
      - S6_SERVICES_READYTIME=50
      - UV_EXTRA_INDEX_URL=https://wheels.home-assistant.io/musllinux-index/
      - S6_SERVICES_GRACETIME=240000
      - UV_SYSTEM_PYTHON=true
      - UV_NO_CACHE=true
PUID=1000
PGID=1000
TZ=America/New_York
USERDIR=/home/reid.sprite
DOCKERDIR=/mnt/docker
HOSTNAME=citrus
HOSTNAME_NODE1=bitter-orange
HOSTNAME_NODE2=sweet-orange
HOSTNAME_NODE3=blood-orange
DOMAIN=reidsprite.com
LOCAL_IPS=127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
CLOUDFLARE_IPS=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
    deploy:
      mode: replicated 
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.ha.rule=Host(`ha.$HOSTNAME.$DOMAIN`)
        - traefik.http.routers.ha.entrypoints=websecure
        - traefik.http.routers.ha.tls=true
        - traefik.http.routers.ha.tls.certresolver=cloudflare
        - traefik.http.routers.ha.service=ha
        - traefik.http.services.ha.loadbalancer.server.port=8321
networks:
  traefik-public:
    external: true