
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --credentials-file /run/secrets/cf_tunnel_token run 178ea871-a479-4255-bec4-af3a576bcdfb
    secrets:
      - cf_tunnel_token
    networks:
      - traefik-public
    dns:
      - 192.168.1.11
      - 192.168.1.22
    deploy:
      replicas: 2
secrets:
  cf_tunnel_token:
    external: true
networks:
  traefik-public:
    external: true