
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --credentials-file /run/secrets/cf_tunnel_token run 178ea871-a479-4255-bec4-af3a576bcdfb
    secrets:
      - cf_tunnel_token
    networks:
      - swarm-network
    dns:
      - 192.168.1.11
      - 192.168.1.22
      - 192.168.1.33
      - 192.168.1.44
    deploy:
      replicas: 2
      #placement:
      #  constraints:
      #    - node.role == manager
      #labels:
      #  - traefik.http.services.cloudflared.loadbalancer.server.port=9000
secrets:
  cf_tunnel_token:
    external: true
networks:
  swarm-network:
    external: true