services:
    postgres:
        image: postgres
        restart: unless-stopped
        stop_grace_period: 30s
        environment:
            POSTGRES_USER: semaphore
            POSTGRES_PASSWORD: 9ddbe040551488770d6f7a5a61200694
            POSTGRES_DB: semaphore
        volumes:
          - /volume1/docker/postgres/data:/var/lib/postgresql/data
        networks:
            - bridge_ipv6

    semaphore:
        image: semaphoreui/semaphore:latest
        restart: unless-stopped
        depends_on:
          - postgres
        ports:
          - 3000:3000
        environment:
            PUID: 1026
            PGID: 100
            SEMAPHORE_DB_DIALECT: postgres
            SEMAPHORE_DB_HOST: postgres
            SEMAPHORE_DB_NAME: semaphore
            SEMAPHORE_DB_USER: semaphore
            SEMAPHORE_DB_PASS: 9ddbe040551488770d6f7a5a61200694
            SEMAPHORE_DB_OPTIONS: '{"sslmode":"disable"}'
            # SEMAPHORE_ADMIN: admin
            # SEMAPHORE_ADMIN_PASSWORD: "23WhiteCn!Star"
            # SEMAPHORE_ADMIN_NAME: Reid Sprite
            # SEMAPHORE_ADMIN_EMAIL: reid@reidsprite.com
            SEMAPHORE_ACCESS_KEY_ENCRYPTION: 89ybj/fT3BaGwZgOdSLb/8skLBLZwleYRqKjI7LkbMw=
            SEMAPHORE_WEB_ROOT: '/'
            # SEMAPHORE_OIDC_ACTIVATED: "yes"
            # SEMAPHORE_OIDC_DISPLAY_NAME: "Sign in with authentik"
            # SEMAPHORE_OIDC_PROVIDER_NAME: "authentik"
            # SEMAPHORE_OIDC_PROVIDER_URL: "https://auth.reidsprite.com/application/o/semaphore-semaphore/"
            # SEMAPHORE_OIDC_CLIENT_ID: "sn10N2nf52qoWzlV7KsxWZUXMVAObVTHgzDdKSpl"
            # SEMAPHORE_OIDC_CLIENT_SECRET: "hcxgKQJFUDjkKtMdAjS1UD9erTfdFcUVa0B8Fh4Ry8dhZKveB0AnYurfRsxsRhBCCuH8p2PerJOffMALvCWvyi4Kn69FNjlAlVLPVMcAMHP2uebknkMRnrric8DQdgWa"
            # SEMAPHORE_OIDC_REDIRECT_URL: "https://semaphore.citrus.reidsprite.com/api/auth/oidc/authentik/redirect/"
            # SEMAPHORE_OIDC_SCOPES: "openid profile email"
            # SEMAPHORE_OIDC_USERNAME_CLAIM: "username"
            # SEMAPHORE_OIDC_NAME_CLAIM: "name"
            # SEMAPHORE_OIDC_EMAIL_CLAIM: "email"          
            # ANSIBLE_HOST_KEY_CHECKING: False
        labels:
          - traefik.enable=true
          - traefik.http.routers.semaphore.rule=Host(`semaphore.$HOSTNAME.$DOMAIN`)
          - traefik.http.routers.semaphore.entrypoints=websecure
          - traefik.http.routers.semaphore.tls=true
          - traefik.http.routers.semaphore.tls.certresolver=cloudflare
          - traefik.http.routers.semaphore.service=semaphore
          - traefik.http.services.semaphore.loadbalancer.server.port=3000
        volumes:
            - /volume1/docker/semaphore/data:/data:rw
            - /volume1/docker/semaphore/config:/etc/semaphore:rw
            - /volume1/docker/semaphore/tmp:/tmp/semaphore:rw
        networks:
            - bridge_ipv6

networks:
    bridge_ipv6:
      external: true