---
- name: Generate SSH keys on all nodes
  hosts: all
  become: yes
  tasks:
    - name: Generate SSH key pair
      ansible.builtin.openssh_keypair:
        path: /home/{{ ansible_user }}/.ssh/id_rsa
        type: rsa
        size: 2048
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      register: ssh_key

    - name: Display public key
      debug:
        msg: "{{ ssh_key.public_key }}"