---
- name: Generate and Install SSH keys
  hosts: localhost
  tasks:
    - name: Generate SSH key pair
      ansible.builtin.openssh_keypair:
        path: /home/{{ ansible_user }}/.ssh/id_rsa
        type: rsa
        size: 2048
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      register: ssh_key

- name: Install SSH keys on Orange nodes
  hosts: orange
  tasks:
    - name: Append public key to authorized_users file
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user }}/.ssh/authorized_users
        line: "{{ ssh_key.public_key }}"
        create: yes