---
- name: Install Docker and configure GlusterFS
  hosts: orange
  become: yes
  tasks:

    - name: Create GlusterFS brick folder
      file:
        path: /home/{{ ansible_user }}/Gluster/gv0
        state: directory
        mode: '0755'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install GlusterFS
      apt:
        name: glusterfs-server
        state: present

    - name: Enable service glusterd and ensure it is not masked
      ansible.builtin.systemd_service:
        name: glusterd
        enabled: true
        masked: no

    - name: Start service glusterd
      ansible.builtin.systemd_service:
        name: glusterd
        state: started

    - name: Add GlusterFS brick to fstab
      ansible.posix.mount:
        path: /home/{{ ansible_user }}/Gluster/gv0
        src: localhost:/gv0
        fstype: glusterfs
        opts: defaults
        state: present

    - name: Mount GlusterFS brick
      command: mount -a

    - name: Check for existing Gluster volumes
      shell: gluster volume list
      register: gluster_volumes
      changed_when: false

    - name: Create Gluster volume if none exists
      shell: gluster volume create gv0 replica 2 {{ ansible_hostname }}:/home/{{ ansible_user }}/Gluster/gv0 force
      when: gluster_volumes.stdout == ""

    - name: Start Gluster volume
      shell: gluster volume start gv0
      when: gluster_volumes.stdout == ""

    - name: Join existing Gluster volume
      shell: gluster peer probe {{ item }}
      with_items: "{{ groups['orange'] }}"
      when: gluster_volumes.stdout != ""

    - name: Check if /mnt/docker is mounted
      command: mountpoint -q /mnt/docker
      register: mount_status
      changed_when: false

    - name: Fail if /mnt/docker is not mounted
      fail:
        msg: "/mnt/docker is not mounted"
      when: mount_status.rc != 0

    - name: Create Docker file structure
      file:
        path: /mnt/docker/{{ item }}
        state: directory
        mode: '0755'
      with_items:
        - appdata
        - compose
        - secrets

    - name: Install required packages for Docker
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: latest

    - name: Ensure Docker service is started
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: yes

    - name: Join Docker swarm
      shell: docker swarm join --token {{ swarm_token }} {{ manager_ip }}:2377
      when: swarm_token is defined and manager_ip is defined and swarm_token != "" and manager_ip != ""