---
- name: Install Docker and configure GlusterFS
  hosts: orange
  become: yes
  tasks:
    - name: Create glusterfs data folder
      file:
        path: /mnt/docker
        state: directory
        mode: '0755'

    - name: Install GlusterFS
      apt:
        name: glusterfs-server
        state: present

    - name: Enable and start GlusterFS service
      systemd:
        name: glusterd
        enabled: yes
        state: started

    - name: Check if GlusterFS is running
      shell: systemctl is-active glusterd
      register: glusterfs_status
      changed_when: false

    - name: Fail if GlusterFS is not running
      fail:
        msg: "GlusterFS is not running"
      when: glusterfs_status.stdout != "active"

    - name: Create GlusterFS brick folder
      file:
        path: ~/glusterfs/gv0
        state: directory
        mode: '0755'

    - name: Add GlusterFS brick to fstab
      mount:
        path: ~/glusterfs/gv0
        src: localhost:/gv0
        fstype: glusterfs
        opts: defaults
        state: present

    - name: Mount GlusterFS brick
      command: mount -a

    - name: Check for existing Gluster volumes
      shell: gluster volume list
      register: gluster_volumes
      changed_when: false

    - name: Create Gluster volume if none exists
      shell: gluster volume create gv0 replica 2 {{ ansible_hostname }}:/glusterfs/gv0 force
      when: gluster_volumes.stdout == ""

    - name: Start Gluster volume
      shell: gluster volume start gv0
      when: gluster_volumes.stdout == ""

    - name: Join existing Gluster volume
      shell: gluster peer probe {{ item }}
      with_items: "{{ groups['orange'] }}"
      when: gluster_volumes.stdout != ""

    - name: Create Docker file structure
      file:
        path: /mnt/docker/{{ item }}
        state: directory
        mode: '0755'
      with_items:
        - appdata
        - compose
        - secrets

    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: latest

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m`
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check if /mnt/docker is mounted
      command: mountpoint -q /mnt/docker
      register: mount_status
      changed_when: false

    - name: Fail if /mnt/docker is not mounted
      fail:
        msg: "/mnt/docker is not mounted"
      when: mount_status.rc != 0

    - name: Join Docker swarm
      shell: docker swarm join --token {{ swarm_token }} {{ manager_ip }}:2377
      when: swarm_token is defined and manager_ip is defined