---
- name: Install Docker and configure GlusterFS
  hosts: orange
  become: yes
  tasks:

    - name: Create GlusterFS brick folder
      file:
        path: /home/{{ ansible_user }}/Gluster/gv0
        state: directory
        mode: '0755'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install GlusterFS and IPTables
      apt:
        name: 
          - glusterfs-server
          - iptables
        state: present

    - name: Enable service glusterd and ensure it is not masked
      ansible.builtin.systemd:
        name: glusterd
        enabled: true
        masked: no

    - name: Start service glusterd
      ansible.builtin.systemd_service:
        name: glusterd
        state: started

    # - name: Add GlusterFS brick to fstab
    #   ansible.posix.mount:
    #     path: /home/{{ ansible_user }}/Gluster/gv1
    #     src: localhost:/gv1
    #     fstype: glusterfs
    #     opts: defaults
    #     state: present

    # - name: Mount GlusterFS brick
    #   command: mount -a
    
    - name: Configure firewall
      ansible.builtin.iptables:
        chain: INPUT
        protocol: all
        source: "{{ ansible_default_ipv4.address }}"
        jump: ACCEPT
        state: present

    - name: Configure peers
      gluster.gluster.gluster_peer:
        state: present
        nodes:
          - "{{ item }}"
      loop: "{{ groups['orange'] }}"

    # - name: Create Gluster volume
    #   gluster.gluster.gluster_volume:
    #     state: present
    #     name: gv1
    #     bricks: /home/{{ ansible_user }}/Gluster/gv1
    #     rebalance: yes
    #     cluster:
    #       - bitter-orange
    #       - blood-orange
    #       - navel-orange
    #       - sweet-orange
    #   run_once: true

    # - name: Start gluster volume
    #   gluster.gluster.gluster_volume:
    #     state: started
    #     name: gv1