---
- name: Test variables
  hosts: orange
  become: yes
  tasks:

    - name: Get DEBID
      ansible.builtin.shell: 
        cmd: grep 'VERSION_ID=' /etc/os-release | cut -d '=' -f 2 | tr -d '\"'
      register: debid
    
    - name: Get DEBARCH
      ansible.builtin.shell: 
        cmd: dpkg --print-architecture
      register: debarch

    - name: Add Gluster repo to apt
      block:
        - name: gluster | no apt key
          ansible.builtin.shell:
            cmd: wget -O - https://download.gluster.org/pub/gluster/glusterfs/9/rsa.pub | apt-key add -
        - name: gluster | apt source
          ansible.builtin.apt_repository:
            repo: 'deb [arch={{ debarch.stdout }}] https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/{{ debid.stdout }}/{{ debarch.stdout }}/apt {{ ansible_distribution_release }} main'
            state: present