---
- name: Test variables
  hosts: orange
  become: yes
  tasks:

    - name: Get DEBID
      ansible.builtin.shell: 
        cmd: grep 'VERSION_ID=' /etc/os-release | cut -d '=' -f 2 | tr -d '\"'
      register: debid

    - name: Get DEBVER
      ansible.builtin.shell: 
        cmd: grep 'VERSION=' /etc/os-release | grep -Eo '[a-z]+'
      register: debver
    
    - name: Get DEBARCH
      ansible.builtin.shell: 
        cmd: dpkg --print-architecture
      register: debarch

    - name:  Add GlusterFS repository
      apt_repository:
        repo:  'deb [signed-by=/etc/apt/trusted.gpg.d/gluster.asc] https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/{{ debid.stdout }}/{{ debarch.stdout }}/apt {{ debver.stdout }} main'
        state: present
        update_cache: yes