---
- name: Update and upgrade apt packages
  hosts: orange
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        autoclean: yes
        autoremove: yes
        purge: yes
        clean: yes
        upgrade: full        
        state: latest