---
  - hosts: master
    become: yes
    tasks:
      - name: Install public keys
        ansible.posix.authorized_key:
          user: reid.sprite
          state: present
          key: "{{ lookup('file', '/data/ansible_id_rsa.pub') }}"
  - hosts: orange
    become: yes
    tasks:
      - name: Install public keys
        ansible.posix.authorized_key:
          user: reid.sprite
          state: present
          key: "{{ lookup('file', '/data/ansible_id_rsa.pub') }}"