services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - '$DOCKERDIR/ollama/data:/root/.ollama'
    container_name: ollama
    hostname: ollama
    ports:
      - 11434:11434
    tty: true
    restart: unless-stopped
    networks:
      'bridge_ipv6'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.ollama.rule: 'Host(`ollama.$DOMAIN`)'
      traefik.http.routers.ollama.service: 'ollama'
      traefik.http.services.ollama.loadbalancer.server.port: '11434'

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - '$DOCKERDIR/open-webui/data:/app/backend/data'
    depends_on:
      - ollama
    environment:
      OLLAMA_BASE_URL: 'http://ollama:11434'
      WEBUI_SECRET_KEY: '243tuil234gut2i5l34gt3t5hiuohgoigeho'
    ports:
      - 3000:8080
    #extra_hosts:
    #  - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - bridge_ipv6
    labels:
      traefik.enable: 'true'
      traefik.http.routers.open-webui.rule: 'Host(`ai.$DOMAIN`)'
      traefik.http.routers.open-webui.service: 'open-webui'
      traefik.http.services.open-webui.loadbalancer.server.port: '8080'

networks:
  bridge_ipv6:
    external: true