services:
  infinitude:
    image: nebulous/infinitude
    container_name: infinitude
    hostname: infinitude
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_ADMIN
    ports:
      - target: 3000
        published: 3010
        protocol: tcp
    volumes:
      - /mnt/docker/appdata/infinitude/state:/infinitude/state
      - /run/udev:/run/udev:ro
      - /dev/ttySC0:/dev/ttySC0
    environment:
      - APP_SECRET=Pogotudinal
      - PASS_REQS=300
      - MODE=development
      - LOGLEVEL=debug
      - SERIAL_TTY=/dev/ttySC0
      #- SERIAL_SOCKET=192.168.1.47:23
    devices:
      - /dev/ttySC0:/dev/ttySC0
      - /dev/gpiomem:/dev/gpiomem