services:
  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    hostname: influxdb
    restart: unless-stopped
    ports:
      - target: 8086
        published: 8086
        protocol: tcp
        mode: host
    volumes:
      - $DOCKERDIR/appdata/influxdb2/data:/var/lib/influxdb2
      - $DOCKERDIR/appdata/influxdb2/config:/etc/influxdb2
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.influxdb.rule=Host(`influxdb.$DOMAIN`)
        - traefik.http.routers.influxdb.service=influxdb
        - traefik.http.services.influxdb.loadbalancer.server.port=8086  
networks:
  traefik-public:
    external: true