services:
  traefik-kop:
    image: ghcr.io/jittering/traefik-kop:latest
    hostname: traefik-kop
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_ADDR=orange:6379
      - BIND_IP=192.168.1.10
    networks:
      - bridge_ipv6
    dns:
      - 192.168.1.11
      - 192.168.1.22

networks:
  bridge_ipv6:
    external: true
    enable_ipv6: false